//
// Created by Patrick Wu on 05/03/2020.
//

#ifndef GOSH_FHIRWORKS2020_DATAMASKER_FILTER_HH
#define GOSH_FHIRWORKS2020_DATAMASKER_FILTER_HH


class filter {

};


#endif //GOSH_FHIRWORKS2020_DATAMASKER_FILTER_HH
