//
// Created by Patrick Wu on 05/03/2020.
//

#ifndef GOSH_FHIRWORKS2020_DATAMASKER_MULTIPLE_BIRTH_GENERATOR_HH
#define GOSH_FHIRWORKS2020_DATAMASKER_MULTIPLE_BIRTH_GENERATOR_HH

class multiple_birth_generator {
    
};

#endif //GOSH_FHIRWORKS2020_DATAMASKER_MULTIPLE_BIRTH_GENERATOR_HH
