//
// Created by Patrick Wu on 03/03/2020.
//

#ifndef GOSH_FHIRWORKS2020_DATAMASKER_GENDER_HH
#define GOSH_FHIRWORKS2020_DATAMASKER_GENDER_HH

enum gender {
    MALE = 0,
    FEMALE = 1,
    OTHER = 2
};

#endif //GOSH_FHIRWORKS2020_DATAMASKER_GENDER_HH
